// ─── Static data — formations, formation posts, blog posts ────────────────────

// ── Formations ────────────────────────────────────────────────────────────────
export const FORMATIONS = {
  11: {
    "4-4-2": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:80, y:72, pos:"RB" }, { id:"rcb", x:62, y:74, pos:"CB" },
      { id:"lcb", x:38, y:74, pos:"CB" }, { id:"lb",  x:20, y:72, pos:"LB" },
      { id:"rm",  x:82, y:52, pos:"RM" }, { id:"rcm", x:62, y:52, pos:"CM" },
      { id:"lcm", x:38, y:52, pos:"CM" }, { id:"lm",  x:18, y:52, pos:"LM" },
      { id:"rs",  x:62, y:24, pos:"ST" }, { id:"ls",  x:38, y:24, pos:"ST" },
    ],
    "4-3-3": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:80, y:72, pos:"RB" }, { id:"rcb", x:62, y:74, pos:"CB" },
      { id:"lcb", x:38, y:74, pos:"CB" }, { id:"lb",  x:20, y:72, pos:"LB" },
      { id:"rcm", x:68, y:52, pos:"CM" }, { id:"cm",  x:50, y:56, pos:"CM" },
      { id:"lcm", x:32, y:52, pos:"CM" },
      { id:"rw",  x:78, y:22, pos:"RW" }, { id:"st",  x:50, y:16, pos:"ST" },
      { id:"lw",  x:22, y:22, pos:"LW" },
    ],
    "4-2-3-1": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:80, y:74, pos:"RB" }, { id:"rcb", x:62, y:74, pos:"CB" },
      { id:"lcb", x:38, y:74, pos:"CB" }, { id:"lb",  x:20, y:74, pos:"LB" },
      { id:"rdm", x:62, y:60, pos:"DM" }, { id:"ldm", x:38, y:60, pos:"DM" },
      { id:"ram", x:72, y:40, pos:"AM" }, { id:"cam", x:50, y:38, pos:"AM" },
      { id:"lam", x:28, y:40, pos:"AM" },
      { id:"st",  x:50, y:18, pos:"ST" },
    ],
    "3-5-2": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rcb", x:68, y:72, pos:"CB" }, { id:"cb",  x:50, y:72, pos:"CB" },
      { id:"lcb", x:32, y:72, pos:"CB" },
      { id:"rwb", x:84, y:52, pos:"RWB"},{ id:"rcm", x:64, y:52, pos:"CM" },
      { id:"cm",  x:50, y:48, pos:"CM" }, { id:"lcm", x:36, y:52, pos:"CM" },
      { id:"lwb", x:16, y:52, pos:"LWB"},
      { id:"rs",  x:62, y:22, pos:"ST" }, { id:"ls",  x:38, y:22, pos:"ST" },
    ],
    "3-4-3": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rcb", x:68, y:72, pos:"CB" }, { id:"cb",  x:50, y:72, pos:"CB" },
      { id:"lcb", x:32, y:72, pos:"CB" },
      { id:"rm",  x:78, y:52, pos:"RM" }, { id:"rcm", x:60, y:52, pos:"CM" },
      { id:"lcm", x:40, y:52, pos:"CM" }, { id:"lm",  x:22, y:52, pos:"LM" },
      { id:"rw",  x:72, y:22, pos:"RW" }, { id:"st",  x:50, y:16, pos:"ST" },
      { id:"lw",  x:28, y:22, pos:"LW" },
    ],
    "4-1-4-1": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:80, y:74, pos:"RB" }, { id:"rcb", x:62, y:74, pos:"CB" },
      { id:"lcb", x:38, y:74, pos:"CB" }, { id:"lb",  x:20, y:74, pos:"LB" },
      { id:"dm",  x:50, y:60, pos:"DM" },
      { id:"rm",  x:80, y:44, pos:"RM" }, { id:"rcm", x:62, y:44, pos:"CM" },
      { id:"lcm", x:38, y:44, pos:"CM" }, { id:"lm",  x:20, y:44, pos:"LM" },
      { id:"st",  x:50, y:20, pos:"ST" },
    ],
    "4-5-1": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:80, y:74, pos:"RB" }, { id:"rcb", x:62, y:74, pos:"CB" },
      { id:"lcb", x:38, y:74, pos:"CB" }, { id:"lb",  x:20, y:74, pos:"LB" },
      { id:"rm",  x:82, y:50, pos:"RM" }, { id:"rcm", x:64, y:50, pos:"CM" },
      { id:"cm",  x:50, y:50, pos:"CM" }, { id:"lcm", x:36, y:50, pos:"CM" },
      { id:"lm",  x:18, y:50, pos:"LM" },
      { id:"st",  x:50, y:20, pos:"ST" },
    ],
    "3-4-2-1": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rcb", x:68, y:74, pos:"CB" }, { id:"cb",  x:50, y:74, pos:"CB" },
      { id:"lcb", x:32, y:74, pos:"CB" },
      { id:"rm",  x:78, y:54, pos:"RM" }, { id:"rcm", x:60, y:54, pos:"CM" },
      { id:"lcm", x:40, y:54, pos:"CM" }, { id:"lm",  x:22, y:54, pos:"LM" },
      { id:"rss", x:62, y:32, pos:"SS" }, { id:"lss", x:38, y:32, pos:"SS" },
      { id:"st",  x:50, y:16, pos:"ST" },
    ],
    "5-3-2": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rwb", x:84, y:72, pos:"RWB"},{ id:"rcb", x:67, y:74, pos:"CB" },
      { id:"cb",  x:50, y:76, pos:"CB" }, { id:"lcb", x:33, y:74, pos:"CB" },
      { id:"lwb", x:16, y:72, pos:"LWB"},
      { id:"rcm", x:65, y:50, pos:"CM" }, { id:"cm",  x:50, y:50, pos:"CM" },
      { id:"lcm", x:35, y:50, pos:"CM" },
      { id:"rs",  x:62, y:22, pos:"ST" }, { id:"ls",  x:38, y:22, pos:"ST" },
    ],
    "5-4-1": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rwb", x:84, y:72, pos:"RWB"},{ id:"rcb", x:67, y:74, pos:"CB" },
      { id:"cb",  x:50, y:76, pos:"CB" }, { id:"lcb", x:33, y:74, pos:"CB" },
      { id:"lwb", x:16, y:72, pos:"LWB"},
      { id:"rm",  x:78, y:50, pos:"RM" }, { id:"rcm", x:60, y:50, pos:"CM" },
      { id:"lcm", x:40, y:50, pos:"CM" }, { id:"lm",  x:22, y:50, pos:"LM" },
      { id:"st",  x:50, y:20, pos:"ST" },
    ],
  },
  9: {
    "3-3-2": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:75, y:72, pos:"RB" }, { id:"cb",  x:50, y:72, pos:"CB" },
      { id:"lb",  x:25, y:72, pos:"LB" },
      { id:"rm",  x:72, y:50, pos:"RM" }, { id:"cm",  x:50, y:50, pos:"CM" },
      { id:"lm",  x:28, y:50, pos:"LM" },
      { id:"rs",  x:65, y:24, pos:"ST" }, { id:"ls",  x:35, y:24, pos:"ST" },
    ],
    "3-2-3": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:75, y:72, pos:"RB" }, { id:"cb",  x:50, y:72, pos:"CB" },
      { id:"lb",  x:25, y:72, pos:"LB" },
      { id:"rcm", x:65, y:52, pos:"CM" }, { id:"lcm", x:35, y:52, pos:"CM" },
      { id:"rw",  x:75, y:24, pos:"RW" }, { id:"st",  x:50, y:18, pos:"ST" },
      { id:"lw",  x:25, y:24, pos:"LW" },
    ],
    "2-3-3": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rcb", x:65, y:74, pos:"CB" }, { id:"lcb", x:35, y:74, pos:"CB" },
      { id:"rm",  x:75, y:52, pos:"RM" }, { id:"cm",  x:50, y:52, pos:"CM" },
      { id:"lm",  x:25, y:52, pos:"LM" },
      { id:"rw",  x:72, y:24, pos:"RW" }, { id:"st",  x:50, y:18, pos:"ST" },
      { id:"lw",  x:28, y:24, pos:"LW" },
    ],
    "4-2-2": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:78, y:72, pos:"RB" }, { id:"rcb", x:60, y:72, pos:"CB" },
      { id:"lcb", x:40, y:72, pos:"CB" }, { id:"lb",  x:22, y:72, pos:"LB" },
      { id:"rcm", x:65, y:50, pos:"CM" }, { id:"lcm", x:35, y:50, pos:"CM" },
      { id:"rs",  x:65, y:24, pos:"ST" }, { id:"ls",  x:35, y:24, pos:"ST" },
    ],
    "2-4-2": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rcb", x:65, y:74, pos:"CB" }, { id:"lcb", x:35, y:74, pos:"CB" },
      { id:"rm",  x:78, y:52, pos:"RM" }, { id:"rcm", x:58, y:52, pos:"CM" },
      { id:"lcm", x:42, y:52, pos:"CM" }, { id:"lm",  x:22, y:52, pos:"LM" },
      { id:"rs",  x:65, y:24, pos:"ST" }, { id:"ls",  x:35, y:24, pos:"ST" },
    ],
    "3-4-1": [
      { id:"gk",  x:50, y:90, pos:"GK" },
      { id:"rb",  x:75, y:72, pos:"RB" }, { id:"cb",  x:50, y:72, pos:"CB" },
      { id:"lb",  x:25, y:72, pos:"LB" },
      { id:"rm",  x:78, y:52, pos:"RM" }, { id:"rcm", x:58, y:52, pos:"CM" },
      { id:"lcm", x:42, y:52, pos:"CM" }, { id:"lm",  x:22, y:52, pos:"LM" },
      { id:"st",  x:50, y:20, pos:"ST" },
    ],
  },
  7: {
    "3-2-1": [
      { id:"gk", x:50, y:88, pos:"GK" },
      { id:"rb", x:72, y:70, pos:"RB" }, { id:"cb", x:50, y:70, pos:"CB" },
      { id:"lb", x:28, y:70, pos:"LB" },
      { id:"rm", x:68, y:48, pos:"CM" }, { id:"lm", x:32, y:48, pos:"CM" },
      { id:"st", x:50, y:22, pos:"ST" },
    ],
    "2-3-1": [
      { id:"gk",  x:50, y:88, pos:"GK" },
      { id:"rcb", x:65, y:72, pos:"CB" }, { id:"lcb", x:35, y:72, pos:"CB" },
      { id:"rm",  x:75, y:50, pos:"RM" }, { id:"cm",  x:50, y:50, pos:"CM" },
      { id:"lm",  x:25, y:50, pos:"LM" },
      { id:"st",  x:50, y:22, pos:"ST" },
    ],
    "2-2-2": [
      { id:"gk",  x:50, y:88, pos:"GK" },
      { id:"rcb", x:65, y:72, pos:"CB" }, { id:"lcb", x:35, y:72, pos:"CB" },
      { id:"rcm", x:65, y:52, pos:"CM" }, { id:"lcm", x:35, y:52, pos:"CM" },
      { id:"rs",  x:65, y:22, pos:"ST" }, { id:"ls",  x:35, y:22, pos:"ST" },
    ],
    "3-1-2": [
      { id:"gk", x:50, y:88, pos:"GK" },
      { id:"rb", x:72, y:70, pos:"RB" }, { id:"cb", x:50, y:70, pos:"CB" },
      { id:"lb", x:28, y:70, pos:"LB" },
      { id:"cm", x:50, y:50, pos:"CM" },
      { id:"rs", x:65, y:22, pos:"ST" }, { id:"ls", x:35, y:22, pos:"ST" },
    ],
    "1-3-2": [
      { id:"gk",  x:50, y:88, pos:"GK" },
      { id:"cb",  x:50, y:72, pos:"CB" },
      { id:"rm",  x:75, y:52, pos:"RM" }, { id:"cm",  x:50, y:52, pos:"CM" },
      { id:"lm",  x:25, y:52, pos:"LM" },
      { id:"rs",  x:65, y:22, pos:"ST" }, { id:"ls",  x:35, y:22, pos:"ST" },
    ],
    "2-3-2": [
      { id:"gk",  x:50, y:88, pos:"GK" },
      { id:"rcb", x:65, y:72, pos:"CB" }, { id:"lcb", x:35, y:72, pos:"CB" },
      { id:"rm",  x:75, y:50, pos:"RM" }, { id:"cm",  x:50, y:50, pos:"CM" },
      { id:"lm",  x:25, y:50, pos:"LM" },
      { id:"rs",  x:67, y:22, pos:"ST" }, { id:"ls",  x:33, y:22, pos:"ST" },
    ],
  },
  5: {
    "1-2-1": [
      { id:"gk", x:50, y:88, pos:"GK" },
      { id:"cb", x:50, y:68, pos:"CB" },
      { id:"rm", x:72, y:46, pos:"CM" }, { id:"lm", x:28, y:46, pos:"CM" },
      { id:"st", x:50, y:22, pos:"ST" },
    ],
    "2-1-1": [
      { id:"gk", x:50, y:88, pos:"GK" },
      { id:"rd", x:67, y:70, pos:"CB" }, { id:"ld", x:33, y:70, pos:"CB" },
      { id:"cm", x:50, y:50, pos:"CM" },
      { id:"st", x:50, y:22, pos:"ST" },
    ],
    "1-1-2": [
      { id:"gk", x:50, y:88, pos:"GK" },
      { id:"cb", x:50, y:70, pos:"CB" },
      { id:"cm", x:50, y:50, pos:"CM" },
      { id:"rs", x:67, y:22, pos:"ST" }, { id:"ls", x:33, y:22, pos:"ST" },
    ],
    "2-2": [
      { id:"gk",  x:50, y:88, pos:"GK" },
      { id:"rd",  x:67, y:68, pos:"CB" }, { id:"ld",  x:33, y:68, pos:"CB" },
      { id:"ram", x:67, y:32, pos:"AM" }, { id:"lam", x:33, y:32, pos:"AM" },
    ],
  },
};

export const FORMAT_DEFAULTS = { 11:"4-4-2", 9:"3-3-2", 7:"3-2-1", 5:"1-2-1" };

// ── Formation posts (community seeded content) ────────────────────────────────
export const FORMATION_POSTS = [
  {
    id: "fp-442",
    title: "The 4-4-2: Why It Still Works in Sunday League",
    tag: "Formation",
    body: "The classic 4-4-2 remains one of the best formations for recreational football. Two banks of four give you defensive solidity while the twin strikers offer constant threat. The key is discipline from your midfield four — they need to track back and press as a unit. Works especially well when your wingers are willing to defend.",
    likes: 47,
    formation: "4-4-2",
    author: "FCRoster",
    isGuide: true,
  },
  {
    id: "fp-433",
    title: "Mastering the 4-3-3 — High Press Edition",
    tag: "Formation",
    body: "The 4-3-3 is built for teams that love to press high and attack in numbers. Your three forwards must work as a pressing unit, cutting off passing lanes from the back. The central three in midfield need good fitness — one holding midfielder sits deeper while the other two box-to-box. Devastating when executed well, exhausting when not.",
    likes: 38,
    formation: "4-3-3",
    author: "FCRoster",
    isGuide: true,
  },
  {
    id: "fp-4231",
    title: "4-2-3-1: The Tactical Swiss Army Knife",
    tag: "Formation",
    body: "The 4-2-3-1 offers elite defensive cover (double pivot) and elite attacking support (number 10 + wide players). The two DMs protect the back four and recycle possession, while the attacking three support a lone striker. Works best when your CAM is your best player — give them freedom to roam.",
    likes: 52,
    formation: "4-2-3-1",
    author: "FCRoster",
    isGuide: true,
  },
  {
    id: "fp-352",
    title: "3-5-2: Dominate with Wing-Backs",
    tag: "Formation",
    body: "The 3-5-2 is all about your wing-backs. They must be your fittest players, constantly overlapping in attack and tracking back in defence. Three CBs give you aerial dominance and cover against pace. The midfield three can control the game centrally while the WBs provide the width. Requires disciplined, fit players to execute.",
    likes: 29,
    formation: "3-5-2",
    author: "FCRoster",
    isGuide: true,
  },
];
